apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: alloy-config
  files:
    - config.alloy=./config.alloy
# see https://grafana.com/docs/alloy/latest/configure/kubernetes/#kustomize-considerations
  options:
    disableNameSuffixHash: true
generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
