apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  annotations:
    argocd.argoproj.io/sync-wave: "0"

configMapGenerator:
- name: alloy-config
  files:
    - config.alloy=./config.alloy
  # see https://grafana.com/docs/alloy/latest/configure/kubernetes/#kustomize-considerations
  options:
    disableNameSuffixHash: true
- name: grafana-ini
  files:
    - grafana.ini=./grafana-config.ini
    - datasource.yaml=./grafana-datasource.yaml
