loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: azure
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy

  storage:
    type: azure
    azure:
      # Name of the Azure Blob Storage account
      account_name: ${OBSERV_ACCOUNT_NAME}
      # Key associated with the Azure Blob Storage account
      account_key: ${OBSERV_ACCOUNT_KEY}
      container_name: ${OBSERV_LOKI_CONTAINER_NAME}
      # Comprehensive connection string for Azure Blob Storage account (Can be used to replace endpoint, accountName, and accountKey)
      #connectionString: "connString"
      # Flag indicating whether to use Azure Managed Identity for authentication
      #useManagedIdentity: false
      # Flag indicating whether to use a federated token for authentication
      #useFederatedToken: false
      # Client ID of the user-assigned managed identity (if applicable)
      #userAssignedId: "1234-5678-9012"
      # Timeout duration for requests made to the Azure Blob Storage account (in seconds)
      #requestTimeout: "100"
      # Domain suffix of the Azure Blob Storage service endpoint (e.g., core.windows.net)
      #endpointSuffix: "myj"
    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"

# Disable minio storage
minio:
  enabled: false

deploymentMode: SimpleScalable

singleBinary:
  replicas: 1

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0
