apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-conf
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: 'https://github.com/kabasm/actest.git'
    targetRevision: dev
    path: monitoring/conf
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
